---
- name: Add cran apt key
  apt_key:
    keyserver: '{{apt_key_server}}'
    id: '{{apt_key_id}}'
  
- name: Add cran apt repository
  apt_repository:
    repo: '{{cran_apt_repo}}'
    update_cache: yes

- name: Install r-base
  apt:
    name: r-base
    state: latest