---
- name: Gather facts from host
  setup:
    filter: ansible_*

- name: Add cran apt key
  apt_key:
    keyserver: '{{apt_key_server}}'
    id: '{{apt_key_id}}'
  
- name: Add cran apt repository
  apt_repository:
    repo: '{{cran_apt_repo}}'
    update_cache: yes

- name: Install r-base
  apt:
    name: r-base
    state: latest

# Check for reboot and reboot if necessary
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists

- name: Wait for reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30
  become: false
  when: reboot_required_file.stat.exists