---         
# Install MSSQL repo, key and update cache
- name: Import MS GPG Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Register MSSQL Repo
  get_url:
    url: "{{ ubuntu_server_repo_url }}"
    dest: /etc/apt/sources.list.d/mssql-server.list

- name: Refresh apt-get cache for MSSQL Server repo
  apt:
    update_cache: yes

# Intall MSSQL
- name: Install MSSQL
  apt:
    name: mssql-server
    state: latest

- name: MSSQL Server Setup
  shell: MSSQL_PID="{{ pid }}" MSSQL_SA_PASSWORD="{{ sa_password }}" /opt/mssql/bin/mssql-conf -n setup accept-eula
    
#- name: MSSQL Server setup
#  mssql_conf:
#    setup_sa_password: "{{ sa_password }}"
#    setup_pid: "{{ pid }}"
#    login_name: 'sa'
#    login_password: "{{ sa_password }}"
       
# TSQL endpoint
#- name: set TSQL endpoint port
 # mssql_conf:
 #   name: network.tcpport
 #   value: "{{ tsql_endpoint_port }}"
 #   login_name: 'sa'
 #   login_password: "{{ sa_password }}"

- name: open SQL endpoint in firewall
  ufw:
    port: "{{ tsql_endpoint_port }}"
    proto: tcp
    rule: allow

# Install mssql tools repo and update cache
- name: Install MSSQL tool repo
  get_url:
    url: "{{ ubuntu_tools_repo_url }}"
    dest: /etc/apt/sources.list.d/mssql-tools.list

- name: Refresh apt-get cache for MSSQL tools repo
  apt:
    update_cache: yes

# Install MSSQL-tools
- name: Install MSSQL tools package
  apt:
    name: mssql-tools
    state: latest
  environment:
    ACCEPT_EULA: 'y'

# Install odbc package for local connection
- name: Install UNIXODBC package
  apt:
    name: unixodbc-dev
    state: latest

# Start MSSQL service
- name: Start MSSQL
  service:
    name: mssql-server
    state: started

- name: Install pymssql
  pip:
    name: pymssql
    state: latest

# Create LabKey DB
- name: Create DB for LabKey
  mssql_db:
    login_host: "{{ db_server }}"
    login_user: "{{ jdbcUser }}"
    login_password: "{{ jdbcPass }}"
    login_port: "{{ tsql_endpoint_port }}"
    name: "{{ db_name }}"
    state: present

# Check for reboot and reboot if necessary
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists

- name: Wait for reboot
  local_action: wait_for host={{ ansible_ssh_host  }} state=started port=22 delay=30
  become: false
  when: reboot_required_file.stat.exists


