---
- name: Updates a server
  apt:
    update_cache: yes

- name: Install python software properties
  apt: 
    name: python-software-properties
    state: latest

- name: Add Oracle Java Repo
  apt_repository: 
    repo: 'ppa:webupd8team/java'
    state: present
    update_cache: yes

- name: Accept Java 8 License
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Oracle Java 8
  apt: 
    name: 
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    state: latest
