---
- name: Create LabKey home directory
  file:
    path: "{{ lbky_home }}"
    state: directory
    owner: tomcat
    group: root
    mode: 0755

- name: Create download directory for LabKey pull
  file:
    path: "{{ lbky_download_dir }}"
    state: directory
    mode: 0755

- name: Download and Unarchive LabKey
  unarchive:
    src: "{{ lbky_aws_url }}/{{ lbky_cnprc_file }}"
    dest: "{{ lbky_download_dir }}"
    remote_src: yes

- name: Copy LabKey JAR files to tomcat-home/lib folder
  copy:
    src: "{{ lbky_download_dir }}/{{ lbky_extract }}/tomcat-lib/{{ item }}"
    dest: "{{ tomcat_home }}/lib/"
    owner: tomcat
    group: tomcat
    remote_src: yes
  with_items:
    - jtds.jar
    - mail.jar
    - mysql.jar
    - postgresql.jar
    - labkeyBootstrap.jar

## ansible copy does not do directories recursively, used synchronize (rsync)
- name: Copy LabKey directories to Labkey home
  synchronize:
    src: "{{ lbky_download_dir }}/{{ lbky_extract }}/{{ item }}"
    dest: "{{ lbky_home }}"
  with_items:
    - labkeywebapp
    - modules
    - pipeline-lib
  delegate_to: "{{ inventory_hostname }}"

# synchronize does not allow setting of permissions.
- name: Set directory permissions to Labkey home for tomcat
  file:
    path: "{{ lbky_home }}"
    owner: tomcat
    group: root
    recurse: yes

- name: Copy LabKey XML to tomcat/Catalina/localhost
  copy:
    src: '/home/cnprc/labkey.xml'
    dest: "{{ tomcat_home }}/conf/Catalina/localhost"
    owner: tomcat
    group: tomcat

- name: Reload and pick up config changes for Tomcat Service
  systemd:
    name: tomcat
    state: restarted
    daemon_reload: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists

- name: Wait for reboot
  local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30
  become: false
  when: reboot_required_file.stat.exists
