---
- name: Add Tomcat Group
  group:
    name: tomcat

- name: Add Tomcat User
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    create_home: no

- name: Download and Unarchive Apache Tomcat 8.5.9
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz
    dest: /opt
    remote_src: yes

- name: Move Extracted folder to Tomcat
  command: mv /opt/apache-tomcat-8.5.9 /opt/tomcat

- name: Change Ownership of Tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Change tomcat bin files to executable
  file:
    path: /opt/tomcat/bin
    state: directory
    mode: '+x'
    recurse: yes

- name: Setup Tomcat Service
  blockinfile:
    path: /etc/systemd/system/tomcat.service
    create: yes
    block: |
      [Unit]
      Description=Apache Tomcat 8 Servlet Container
      After=syslog.target network.target

      [Service]
      User=tomcat
      Group=tomcat
      Type=forking
      Environment=CATALINA_PID=/opt/tomcat/tomcat.pid
      Environment=CATALINA_HOME=/opt/tomcat
      Environment=CATALINA_BASE=/opt/tomcat
      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Enable and configure tomcat users
  blockinfile:
    path: /opt/tomcat/conf/tomcat-users.xml
    block: |
      <role rolename="manager-gui/"/>
      <user username="{{ tomcat_mgr_uname }}" password="{{ tomcat_mgr_pword }}" roles="manager-gui,admin-gui"/>
    insertbefore: "</tomcat-users>"

- name: Comment META-INF in manager
  lineinfile:
    path: /opt/tomcat/webapps/manager/META-INF/context.xml
    insertbefore: "{{ item.before }}"
    line: "{{ item.line }}"
  with_items:
    - { before: '\<Valve className\=\"org.apache.catalina.valves.RemoteAddrValve\"', line: '<!--' }
    - { before: '</Context>', line: '-->' }
   
- name: Comment META-INF in host-manager
  lineinfile:
    path: /opt/tomcat/webapps/host-manager/META-INF/context.xml
    insertbefore: "{{ item.before }}"
    line: "{{ item.line }}"
  with_items:
    - { before: '\<Valve className\=\"org.apache.catalina.valves.RemoteAddrValve\"', line: '<!--' }
    - { before: '</Context>', line: '-->' }

- name: Start and enable Tomcat Service
  systemd:
    name: tomcat
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for Tomcat to start
  wait_for:
    port: 8080
              
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists

- name: Wait for reboot
  local_action: wait_for host={{ ansible_ssh_host  }} state=started port=22 delay=30
  become: false
  when: reboot_required_file.stat.exists
