---
- name: Install Python 2.x
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-simplejson)
  register: test
  changed_when: test.stdout

- name: Install python-pip
  apt:
    name: python-pip
    state: latest
  
- name: Updates a server
  apt:
    update_cache: yes

- name: Upgrade a server
  apt:
    upgrade: dist

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
    purge: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Rebooting machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists

- name: Wait for reboot
  local_action: wait_for host={{ ansible_ssh_host  }} state=started port=22 delay=30
  become: false
  when: reboot_required_file.stat.exists

